/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Adam' at '6/8/16 11:53 PM' with Gradle 2.9
 *
 * @author Adam, @date 6/8/16 11:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
